language: ruby
cache: bundler
services:
  - redis-server
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database "Admore-BI_test";' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - rubocop
  - bundle exec rails test
